### ISSUE TITLE
Examples of lookup_send and block_lookup

### ISSUE THREAD

**Issue by GaryMacMinn** [gilman88/xmodem-lib#2]
Hi Thomas,
Do you have any examples of using the lookup_send function and an example block_lookup function? I've been trying to work out how to send a large amount of data from SRAM but not having any luck.
Thanks,
Gary

**Comment by GaryMacMinn** [comment]
I can get it to send a single 128 bytes but I can't work out how to send multiple packets for larger files. Any guidance appreciated.

**Comment by gilman88** [comment]
Hi Gary

here is a block_lookup function from one of my projects:
```
inline word page_num_to_address(byte p) {
  return ((word) p & PAGE_ID_MASK) << PAGE_BITS;
}

void lookup_block(void *blk_id, size_t idSize, byte *data, size_t dataSize) {
  word page_addr = page_num_to_address(*((byte *) blk_id));
  for(byte i = 0; i < PAGE_SIZE; ++i) {
    data[i] = read_byte(page_addr + i);
  }
}
```
Baisically what this is doing is mapping a given block id to the memory addresses of a EEPROM chip and filling the memory pointed to by the data pointer with the data stored in the EEPROM.

For sending `lookup_send` will only take the id you pass to it and use the `block_lookup` function to send just that data in a xmodem transaction, if you want to send more things within the same xmodem transaction you should use the `send_bulk_data` function https://github.com/gilman88/xmodem-lib/blob/1.0.2/README.txt#L177-L202 this is used by all the sending functions internally so you can just take a look at the `lookup_send` and `send` functions to see an example of using this.

Hope this helps :)
