### ISSUE TITLE
Raspberry Pi Pico (RP2040) port

### ISSUE THREAD

**Issue by tleiding** [gilman88/xmodem-lib#4]
Why is a RP2040 port needed? Is this not handled if I use the arduino-pico core?

**Comment by gilman88** [comment]
You certainly can use an arduino-pico core to run this on a RP2040 chip and say case closed, someone already put some effort in this direction https://github.com/gilman88/xmodem-lib/pull/1
However I think a native port would be fun and interesting to do, so I plan to do it one day if no one else does it first :D
