### ISSUE TITLE
Platformio / Arduino library out of date?

### ISSUE THREAD

**Issue by geoffbrucepayne** [gilman88/xmodem-lib#5]
When importing to a project in Platformio, it seems the library won't compile due to default declarations in the cpp that don't appear in the latest Github version of the code.  This can be worked around by referencing the Github repository directly but may cause problems for some users.  May just need to update the linkage to Arduino library manager(?)

**Comment by gilman88** [comment]
Looks like I forgot I needed to change the published version number when I published those fixes in the library.properties file. I've done that now and hopefully the Arduino Library list picks it up this time.

**Comment by gilman88** [comment]
The arduino library list is showing the latest version now
