### ISSUE TITLE
Working example needed

### ISSUE THREAD

**Issue by WA6YDQ** [gilman88/xmodem-lib#6]
Greetings!
I'm using your library on an arduino mega with an SD card attached. Receiving a file from the serial port, and writing it to the SD card works just fine. I can transfer and save large files this way.

I can also send a file (based on your example) from memory. That works fine. However, I'm trying to send files larger than memory.

Sending a file from the SD card to the remote computer is my problem. The most I can send is 128 bytes. I'm just not understanding the procedure. I set up a handler, and defined it as follows:
 bool download_block(void *blk_id, size_t idSize, byte *send_data, size_t dataSize);

I have a routine that opens the file, and tries to send a block at a time. It (obviously) doesn't work - I won't bother posting it.

Can you provide an working example of sending a file not memory limited?

Kurt

**Comment by WA6YDQ** [comment]
Never mind. No longer an issue for me.

**Comment by gilman88** [comment]
Glad you were able to find a solution
