### ISSUE TITLE
Sending more data than I can fit in ram

### ISSUE THREAD

**Issue by polarbub** [gilman88/xmodem-lib#7]
I have a Arduino Mega project that can generate about 96 KB of data that I want to send as a file with this library. This is more than the 8 KB of ram that the Mega has so I can't send it all in one large chunk. Is there some way to send multiple smaller chunks of data that will fit in ram and if not does the xmodem protocol even support this? Would I have to transfer multiple files stitch them back together on the other end?

**Comment by gilman88** [comment]
Hi @polarbub if you can generate the data on device then I would consider using the [Lookup send](https://github.com/gilman88/xmodem-lib/blob/master/README.txt#L102) function.

You will need to create and set a block lookup handler that will be responsible for gathering the next block of data that will be sent in the next xmodem packet. So if you could do something along the lines of generating a block of data, pause while it gets sent out, and continue like this until all the data has been generated then it would still all be part of the same file transfer and show up together in a single file.

Xmodem does not have a limit on the size of files it can send it's just that by default there is no way to uniquely identify each file block (default Xmodem only has 256 unique block labels) nor how big the fully transferred file will be. It also can't resume an interrupted transfer for the same reason.
